services:
  eureka:
    build:
      context: ./microservice-eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - microservice_network
    profiles:
      - infra
      - all

  database:
    build:
      context: database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    networks:
      - microservice_network
    profiles:
      - infra
      - all

  authentification:
    build:
      context: ./microservice-authentification
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - microservice_network
    profiles:
      - microservice
      - all

  booking:
    build:
      context: ./microservice-booking
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - microservice_network
    profiles:
      - microservice
      - all

  listing:
    build:
      context: ./microservice-listing
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - microservice_network
    profiles:
      - microservice
      - all

  tracking:
    build:
      context: ./microservice-tracking
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - microservice_network
    profiles:
      - microservice
      - all

  user_management:
    build:
      context: ./microservice-user_management
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    networks:
      - microservice_network
    profiles:
      - microservice
      - all

networks:
  microservice_network:
    driver: bridge