spring:
  application:
    name: microservice-listing
  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true 
    loadbalancer: 
      enabled: true
  datasource:
    url: jdbc:mysql://database:3306/microservice_db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      validation-timeout: 3000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.default.svc.cluster.local:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}