apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: booking-service
spec:
  hosts:
    - "{{ .Values.virtualservices.hosts }}"
  gateways:
    - {{ .Values.gateway.name }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.virtualservices.booking.prefix }}
      route:
        - destination:
            host: {{ printf "%s.%s.svc.cluster.local" .Values.virtualservices.booking.host .Values.namespace }}
            port:
              number: {{ .Values.virtualservices.booking.port }}