spring:
  application:
    name: microservice-authentification
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    url: jdbc:mysql://database:3306/microservice_db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.default.svc.cluster.local:8761/eureka/
  instance:
    prefer-ip-address: true