apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking
  template:
    metadata:
      labels:
        app: tracking
    spec:
      containers:
        - name: tracking
          image: microservice-airbnb-tracking:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          resources:
            requests:
              cpu: "200m"         
              memory: "256Mi"     
            limits:
              cpu: "500m"         
              memory: "512Mi"     
---
apiVersion: v1
kind: Service
metadata:
  name: tracking
spec:
  selector:
    app: tracking
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tracking-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tracking
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60