name: Microservices Airbnb Jobs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 (or Java version used in your project)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Run tests with Maven
        run: mvn test

  docker:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image for microservice-authentification
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-authentification
          file: ./microservice-authentification/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/authentification:latest

      - name: Build and push Docker image for microservice-booking
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-booking
          file: ./microservice-booking/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/booking:latest

      - name: Build and push Docker image for microservice-listing
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-listing
          file: ./microservice-listing/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/listing:latest

      - name: Build and push Docker image for microservice-tracking
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-tracking
          file: ./microservice-tracking/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tracking:latest

      - name: Build and push Docker image for microservice-user-management
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-user_management
          file: ./microservice-user_management/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-management:latest

  deploy:
    runs-on: ubuntu-22.04
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: minikube start --driver=docker || minikube start --driver=none

      - name: Verify Minikube Status
        run: minikube status

      - name: Use Minikube Docker Daemon
        run: eval $(minikube docker-env)

      - name: Build Docker images
        run: |
          docker build -t authentification:latest ./microservice-authentification
          docker build -t booking:latest ./microservice-booking
          docker build -t listing:latest ./microservice-listing
          docker build -t eureka:latest ./microservice-eureka
          docker build -t tracking:latest ./microservice-tracking
          docker build -t management:latest ./microservice-user_management

      - name: Load Images into Minikube
        run: |
          minikube image load authentification:latest
          minikube image load booking:latest
          minikube image load listing:latest
          minikube image load eureka:latest
          minikube image load tracking:latest
          minikube image load management:latest

      - name: Apply Kubernetes manifests
        run: kubectl apply -f ./k8s-manifests

      - name: Verify Kubernetes Pods
        run: kubectl get pods -A


  port-forward-and-test:
    runs-on: ubuntu-22.04
    needs: deploy
    steps:
      - name: Verify Minikube Status
        run: |
          minikube status
          kubectl cluster-info
      - name: Configure kubeconfig for Minikube
        run: |
          kubectl config use-context minikube
      - name: Wait for All Pods to Be Ready
        run: |
          kubectl wait --for=condition=ready pod --all --namespace=default --timeout=300s
      - name: Port-Forward Services
        run: |
          nohup kubectl port-forward svc/authentification 8081:8081 &
          nohup kubectl port-forward svc/booking 8082:8082 &
          nohup kubectl port-forward svc/listing 8083:8083 &
          nohup kubectl port-forward svc/tracking 8084:8084 &
          nohup kubectl port-forward svc/user-management 8085:8085 &
          sleep 10 # Wait for port forwarding to be ready
      - name: Test /ping Endpoints
        run: |
          curl http://localhost:8081/auth/ping
          curl http://localhost:8082/bookings/ping
          curl http://localhost:8083/listings/ping
          curl http://localhost:8084/tracking/ping
          curl http://localhost:8085/users/ping