name: Microservices Airbnb Jobs

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 (or Java version used in your project)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Run tests with Maven
        run: mvn test

  docker:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-authentification:latest ./microservice-authentification
          docker build -t ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-booking:latest ./microservice-booking
          docker build -t ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-listing:latest ./microservice-listing
          docker build -t ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-eureka:latest ./microservice-eureka
          docker build -t ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-tracking:latest ./microservice-tracking
          docker build -t ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-user_management:latest ./microservice-user_management
          docker build -t ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-database:latest ./microservice-user_management

      - name: Push Docker images to registry
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-authentification:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-booking:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-listing:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-eureka:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-tracking:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-user_management:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-database:latest

  deploy:
    runs-on: ubuntu-22.04
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: minikube start --driver=docker 

      - name: Verify Minikube Status
        run: minikube status

      - name: Use Minikube Docker Daemon
        run: eval $(minikube docker-env)

      - name: Load Docker images into Minikube
        run: |
          minikube image load ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-authentification:latest
          minikube image load ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-booking:latest
          minikube image load ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-listing:latest
          minikube image load ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-eureka:latest
          minikube image load ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-tracking:latest
          minikube image load ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-user_management:latest
          minikube image load ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-database:latest
          minikube image load registry.k8s.io/metrics-server/metrics-server:v0.7.2

      - name: Check images loaded on minikube
        run: minikube image ls

      - name: Apply Kubernetes Database, Eureka and Metric Server manifests
        run: |
          kubectl apply -f ./k8s-manifests/database-deployment.yaml
          kubectl apply -f ./k8s-manifests/metrics-server-deployment.yaml
          kubectl apply -f ./k8s-manifests/eureka-deployment.yaml

      - name: Wait 60 seconds for Database Pod to be Ready
        run: sleep 60

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./k8s-manifests/authentification-deployment.yaml
          kubectl apply -f ./k8s-manifests/booking-deployment.yaml
          kubectl apply -f ./k8s-manifests/listing-deployment.yaml
          kubectl apply -f ./k8s-manifests/tracking-deployment.yaml

      - name: Verify Kubernetes Pods
        run: kubectl get pods -A

      - name: Verify Kubernetes Service
        run: kubectl get svc -A

      - name: Wait 2 minutes for Pods to be Ready
        run: sleep 120

      - name: Describe Database Pod
        run: kubectl describe pod $(kubectl get pods -l app=database -o jsonpath="{.items[0].metadata.name}")

      - name: Fetch and Echo Pod Logs
        run: |
          POD_NAME=$(kubectl get pods -l app=database -o jsonpath='{.items[0].metadata.name}')
          echo "Fetching logs for Pod: $POD_NAME"
          echo "========== POD LOGS =========="
          kubectl logs $POD_NAME || echo "No previous logs available."

      - name: Check Logs for All Pods
        run: |
          for pod in $(kubectl get pods -o name); do
            echo "Logs for $pod:"
            kubectl logs $pod
          done

      - name: Port-Forward Services
        run: |
          kubectl port-forward svc/authentification 8081:8081 &
          kubectl port-forward svc/booking 8082:8082 &
          nohup kubectl port-forward svc/listing 8083:8083 &
          nohup kubectl port-forward svc/tracking 8084:8084 &
          nohup kubectl port-forward svc/user-management 8085:8085 &
          sleep 10 # Wait for port forwarding to be ready
      
      - name: Test /ping Endpoints
        run: |
          curl http://localhost:8081/auth/ping
          curl http://localhost:8082/bookings/ping
          curl http://localhost:8083/listings/ping
          curl http://localhost:8084/tracking/ping
          curl http://localhost:8085/users/ping
