name: Microservices Airbnb Jobs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 (or Java version used in your project)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Run tests with Maven
        run: mvn test

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Verify Docker image 
        run: docker images 

      - name: Build and push Docker image for microservice-authentification
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-authentification
          file: ./microservice-authentification/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/authentification:latest

      - name: Build and push Docker image for microservice-booking
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-booking
          file: ./microservice-booking/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/booking:latest

      - name: Build and push Docker image for microservice-listing
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-listing
          file: ./microservice-listing/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/listing:latest

      - name: Build and push Docker image for microservice-tracking
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-tracking
          file: ./microservice-tracking/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tracking:latest

      - name: Build and push Docker image for microservice-user-management
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-user_management
          file: ./microservice-user_management/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-management:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        uses: azure/setup-kubeconfig@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Apply Kubernetes manifests
        run: kubectl apply -f ./k8s-manifests

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/authentification authentification=${{ secrets.DOCKER_USERNAME }}/microservice-authentification:latest
          kubectl set image deployment/booking booking=${{ secrets.DOCKER_USERNAME }}/microservice-booking:latest
          kubectl set image deployment/listing listing=${{ secrets.DOCKER_USERNAME }}/microservice-listing:latest
          kubectl set image deployment/tracking tracking=${{ secrets.DOCKER_USERNAME }}/microservice-tracking:latest
          kubectl set image deployment/user-management user-management=${{ secrets.DOCKER_USERNAME }}/microservice-user-management:latest
