name: Microservices Airbnb Jobs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 (or Java version used in your project)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Run tests with Maven
        run: mvn test

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image for microservice-authentification
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-authentification
          file: ./microservice-authentification/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/authentification:latest

      - name: Build and push Docker image for microservice-booking
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-booking
          file: ./microservice-booking/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/booking:latest

      - name: Build and push Docker image for microservice-listing
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-listing
          file: ./microservice-listing/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/listing:latest

      - name: Build and push Docker image for microservice-tracking
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-tracking
          file: ./microservice-tracking/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tracking:latest

      - name: Build and push Docker image for microservice-user-management
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-user_management
          file: ./microservice-user_management/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-management:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kind
        uses: helm/kind-action@v1.6.0
        with:
          cluster_name: kind
          wait: true

      - name: Build Docker images
        run: |
          docker build -t authentification:latest ./microservice-authentification
          docker build -t booking:latest ./microservice-booking
          docker build -t listing:latest ./microservice-listing
          docker build -t eureka:latest ./microservice-euraka
          docker build -t tracking:latest ./microservice-tracking
          docker build -t management:latest ./microservice-user_management

      - name: Load Docker images into Kind
        run: |
          kind load docker-image authentification:latest --name kind
          kind load docker-image booking:latest --name kind
          kind load docker-image listing:latest --name kind
          kind load docker-image eureka:latest --name kind
          kind load docker-image tracking:latest --name kind
          kind load docker-image management:latest --name kind

      - name: Apply Kubernetes manifests
        run: kubectl apply -f ./k8s-manifests

      - name: Verify Kubernetes Pods
        run: kubectl get pods -A