name: Microservices Airbnb Jobs

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 (or Java version used in your project)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-authentification:latest ./microservice-authentification
          docker build -t ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-booking:latest ./microservice-booking
          docker build -t ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-listing:latest ./microservice-listing
          docker build -t ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-eureka:latest ./microservice-eureka
          docker build -t ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-tracking:latest ./microservice-tracking
          docker build -t ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-user_management:latest ./microservice-user_management
          docker build -t ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-database:latest ./database

      - name: Push Docker images to registry
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-authentification:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-booking:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-listing:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-eureka:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-tracking:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-user_management:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-database:latest

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Run tests with Maven
        run: mvn test

  deploy:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: minikube start --driver=docker --cpus=4 --memory=8192

      - name: Use Minikube Docker Daemon
        run: eval $(minikube docker-env)

      - name: Load Docker images into Minikube
        run: |
          minikube image load ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-authentification:latest
          minikube image load ${{ secrets.DOCKER_USERNAME }}/microservice-airbnb-database:latest
          minikube image load registry.k8s.io/metrics-server/metrics-server:v0.7.2

      - name: Check images loaded on minikube
        run: minikube image ls

      - name: Apply Kubernetes Database, Eureka and Metric Server manifests
        run: |
          kubectl apply -f ./k8s-manifests/database-deployment.yaml
          kubectl apply -f ./k8s-manifests/metrics-server-deployment.yaml
          kubectl apply -f ./k8s-manifests/eureka-deployment.yaml

      - name: Wait 90 seconds for Database Pod to be Ready
        run: |
          kubectl wait --for=condition=ready pod --all --timeout=90s

      - name: Fetch and Echo Pod Logs
        run: |
          POD_NAME=$(kubectl get pods -l app=database -o jsonpath='{.items[0].metadata.name}')
          echo "Fetching logs for Pod: $POD_NAME"
          echo "========== POD LOGS =========="
          kubectl logs $POD_NAME || echo "No previous logs available."

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./k8s-manifests/authentification-deployment.yaml

      - name: Wait 90 seconds for Pods to be Ready
        run: |
          kubectl wait --for=condition=ready pod -l app=authentification --timeout=90s

      - name: Wait 40 seconds for Pods to be Ready
        run: sleep 40

      - name: Fetch and Echo Pod Logs Authentification
        run: |
          POD_NAME=$(kubectl get pods -l app=authentification -o jsonpath='{.items[0].metadata.name}')
          echo "Fetching logs for Pod: $POD_NAME"
          echo "========== POD LOGS =========="
          kubectl logs $POD_NAME || echo "No previous logs available."

      - name: Verify Kubernetes Pods
        run: kubectl get pods -A

      - name: Verify Kubernetes Service
        run: kubectl get svc -A

      - name: Check Logs for All Pods
        run: |
          for pod in $(kubectl get pods -o name); do
            echo "Logs for $pod:"
            kubectl logs $pod
          done

      - name: Port-Forward Services
        run: |
          kubectl port-forward svc/authentification 8081:8081 &
          sleep 10 # Wait for port forwarding to be ready
      
      - name: Verify Kubernetes Pods
        run: kubectl get pods -A

      - name: Verify Kubernetes Service
        run: kubectl get svc -A

      - name: Check the authentification Service Configuration
        run: |
          POD_NAME=$(kubectl get pods -l app=authentification -o jsonpath='{.items[0].metadata.name}')
          echo "Describe service of pod : $POD_NAME"
          echo "========== Service Describe =========="
          kubectl describe svc $POD_NAME 

      - name: Test /ping Endpoints
        run: |
          kubectl port-forward svc/authentification 8081:8081 &
          response=0 # Initialize the response variable
          for i in {1..10}; do
            echo "Checking http://localhost:8081/auth/ping..."
            response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8081/auth/ping)
            if [ "$response" -eq 200 ]; then
              echo "Port forwarding and service are ready!"
              break
            else
              echo "Waiting for port forwarding or service readiness (HTTP $response)..."
            fi
            sleep 1
          done
          if [ "$response" -ne 200 ]; then
            echo "Service did not become ready. Last HTTP status: $response"
            exit 1
          fi


